<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start date of debt_opening_balance_date</name>
   <tag></tag>
   <elementGuidId>03d42eb4-135f-4f54-9cb1-94234b3e56c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_opening_balance_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_opening_balance_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54bb5654-a494-448c-a3d4-99a01f9bcfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d3a374fb-f5f6-4985-b983-f0a724305852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>9a6a3105-156a-449c-b796-5a94e3b001e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>opening_balance_date</value>
      <webElementGuid>6559ef54-d081-4849-8b97-d8a7ae8d6e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_opening_balance_date</value>
      <webElementGuid>d8148d00-c553-4ec3-b441-6a192d609540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>14b65e02-5782-4aa1-b86a-1eedf2ce8421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>604c3ea8-6f5b-4c4f-824d-dca8cca1bb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_opening_balance_date&quot;)</value>
      <webElementGuid>66ac1047-ae39-4e74-ad84-a82b6ba0d6ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_opening_balance_date']</value>
      <webElementGuid>f40d118e-4472-4e41-a17b-5418e1fe412e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opening_balance_date_holder']/div/div/input</value>
      <webElementGuid>0c36ec3c-7c15-419b-bafb-0adf34d81804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>5532fa24-a7f3-4aa1-a611-785cc7dbfe44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'opening_balance_date' and @id = 'ffInput_opening_balance_date']</value>
      <webElementGuid>7d7109a2-23a8-4929-accf-1b84c395b089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
