<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_I owe this debt to somebody elseI am_93cb18</name>
   <tag></tag>
   <elementGuidId>9e7db002-0cf1-4540-882e-8340510649aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_liability_direction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_liability_direction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5081a979-2b6a-4c6a-bbb5-782a7d97e91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>100dc2f3-a617-4172-a4e4-6c7e314ac064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>liability_direction</value>
      <webElementGuid>806f080d-f21f-49b0-a127-54efd58e512d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_liability_direction</value>
      <webElementGuid>05bc25c7-8e51-4014-ae8e-23d72261a911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9b009a57-ff09-4929-bed8-27d2ee221c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e9e0c948-c76a-4cd8-ad43-92205622a63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I owe this debt to somebody elseI am owed this debt</value>
      <webElementGuid>f2c7f599-6c0c-4013-853a-24b678510a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_liability_direction&quot;)</value>
      <webElementGuid>f26a3458-2f23-4635-a601-d13b188d358c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_liability_direction']</value>
      <webElementGuid>0633f423-564b-453e-a212-fdafe935cca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liability_direction_holder']/div/select</value>
      <webElementGuid>b8bc2a27-0d07-43ce-8aa2-69b6f8bbd503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liability in/out'])[1]/following::select[1]</value>
      <webElementGuid>e4690215-6bf5-44dc-bea9-098db36b6221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I owe amount'])[1]/following::select[1]</value>
      <webElementGuid>0af644ac-8f53-4fe1-a8a0-f0ab36b9ed97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start date of debt'])[1]/preceding::select[1]</value>
      <webElementGuid>dd544023-5bbb-4df2-bfe6-f39c654bdfef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest'])[1]/preceding::select[1]</value>
      <webElementGuid>e71bd93f-f3dc-46cc-ab04-224b4f8111ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>51d7cd1c-6d53-4d9d-b9b0-87349370a80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'liability_direction' and @id = 'ffInput_liability_direction' and (text() = 'I owe this debt to somebody elseI am owed this debt' or . = 'I owe this debt to somebody elseI am owed this debt')]</value>
      <webElementGuid>429fbd16-edc0-41b0-8b72-5835bb0bb1f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
