<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Demo</name>
   <tag></tag>
   <elementGuidId>f40ccf24-ea94-4f04-956e-4fb473e434c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.me-lg-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarResponsive']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>156cf5be-3d94-4819-8071-e3241630f7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link me-lg-3</value>
      <webElementGuid>50d08350-33e2-4227-b453-13ecca8215cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.firefly-iii.org/</value>
      <webElementGuid>58dd0a85-568e-4be2-9de1-186bfefce926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo</value>
      <webElementGuid>2e69a0d0-1dda-4f0f-a47b-2f2affffc3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarResponsive&quot;)/ul[@class=&quot;navbar-nav ms-auto me-4 my-3 my-lg-0&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link me-lg-3&quot;]</value>
      <webElementGuid>755d96b6-18d5-4ec9-b147-5363f7bd5c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarResponsive']/ul/li/a</value>
      <webElementGuid>03637a4e-0384-4d4b-8e39-f225e2a23c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Demo')]</value>
      <webElementGuid>cabc5227-35bb-43f4-a749-cc9bfc5ce606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::a[1]</value>
      <webElementGuid>8441d9cf-57c7-407d-a76d-7de57f7dd985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firefly III'])[1]/following::a[1]</value>
      <webElementGuid>e9283893-c4f9-4e43-b2df-64f2b9b4ed95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentation'])[1]/preceding::a[1]</value>
      <webElementGuid>bf25c4cb-53ed-4b7b-a994-d644912b302a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::a[2]</value>
      <webElementGuid>63caf1bc-95d8-4ac3-9370-c2912f99db5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo']/parent::*</value>
      <webElementGuid>bc19dbe8-2179-4e64-b11b-12926aa660cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.firefly-iii.org/')]</value>
      <webElementGuid>a635d474-c651-4965-a3ee-8222a98a884b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>24d17854-caff-4204-afb5-fbc77a311a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.firefly-iii.org/' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>85b3ab11-48f4-4fac-972c-50c58fbb4f50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
