<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_I owe this debt to somebody elseI am_93cb18</name>
   <tag></tag>
   <elementGuidId>a79258a4-bed6-42f5-8bc8-d180da7bb2c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_liability_direction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_liability_direction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e7314d16-7069-417c-b415-62a623cf3560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>28bf108e-7dbe-45ea-8c61-87ff98a71172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>liability_direction</value>
      <webElementGuid>5606621d-9965-4aaf-b891-8a437fcfe4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_liability_direction</value>
      <webElementGuid>26745a05-c894-496c-baa7-65817a1fbffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b2461d3f-1991-4eca-b6b3-75816825b767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f1234fdf-bcd3-4572-bc0b-2df95fa31506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I owe this debt to somebody elseI am owed this debt</value>
      <webElementGuid>aa348b2d-d5d8-4c4b-9de6-3851bf2baa81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_liability_direction&quot;)</value>
      <webElementGuid>40b8c1ae-c4bb-49eb-a7df-417430d93000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_liability_direction']</value>
      <webElementGuid>153bb1db-e41a-4c91-86b2-7a802eea0fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liability_direction_holder']/div/select</value>
      <webElementGuid>1b1f1e9a-c7ed-4698-aaca-642b565ad69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liability in/out'])[1]/following::select[1]</value>
      <webElementGuid>c6c9947a-36c0-444e-9a41-b837349fcb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I owe amount'])[1]/following::select[1]</value>
      <webElementGuid>c28ae946-11de-4ce8-aefe-b789a6e5ad7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start date of debt'])[1]/preceding::select[1]</value>
      <webElementGuid>c377e9ee-3a69-4c4c-9e82-d3af83ab0348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest'])[1]/preceding::select[1]</value>
      <webElementGuid>736c898a-bd7d-43ee-b83a-d7192fb83001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>a0d5ff0b-a471-47bb-a92c-ceba339819f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'liability_direction' and @id = 'ffInput_liability_direction' and (text() = 'I owe this debt to somebody elseI am owed this debt' or . = 'I owe this debt to somebody elseI am owed this debt')]</value>
      <webElementGuid>34083fb3-c569-463c-beb7-3e8f01ba61f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
