<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_After storing, return here to create _4fc2e2</name>
   <tag></tag>
   <elementGuidId>fe964dfd-e8b8-47cb-af89-6eb84ce3bea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account_return_to_form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account_return_to_form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67506f5a-26b5-461b-adf4-27e71a0f24c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>305eb036-a9a1-4621-8a9d-607b918baedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create_another</value>
      <webElementGuid>a792512f-fe48-438f-a0b7-3b087a155bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account_return_to_form</value>
      <webElementGuid>608e7569-5cdc-41e2-a988-5d1b8616955a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d084d068-1a1c-4e68-b4bf-5a37d2ed464e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account_return_to_form&quot;)</value>
      <webElementGuid>feb38375-ad8d-496b-ae74-a27f94619450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account_return_to_form']</value>
      <webElementGuid>5d448213-d8fd-4d8a-8d65-964299e6a166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='store']/div[2]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>73e29ab0-f0ce-40ac-892a-be7f47ddb6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>dd020828-9204-40ab-bbda-9998a91fce9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'create_another' and @id = 'account_return_to_form']</value>
      <webElementGuid>1dee0cd0-9296-4b13-8ef6-ecb522022528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
