<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Include in net worth_include_net_worth</name>
   <tag></tag>
   <elementGuidId>26b43d7f-1a44-409c-ac20-e3573ecd8b51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_include_net_worth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_include_net_worth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5952a1e4-ce62-4b0d-a3ee-412d1161a352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8a5dd676-10b4-407d-b115-c1a420c27498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>include_net_worth</value>
      <webElementGuid>04c94ab7-e98a-40fa-b019-76002ee7adda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_include_net_worth</value>
      <webElementGuid>001e970a-abb1-4b48-bb8f-0e7fd210968f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>44322b93-b16d-4c68-96ae-bdc20153f1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_include_net_worth&quot;)</value>
      <webElementGuid>78e4bc8a-1946-4ab9-ae2e-569613affd29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_include_net_worth']</value>
      <webElementGuid>71b79078-4632-4e42-82c9-69e31b7b877b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='include_net_worth_holder']/div/div/label/input</value>
      <webElementGuid>2389f57f-4e46-4dcd-8a3a-5531a45cbd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>1df888de-c37b-4f8e-8dc2-ddb2c20b5e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'include_net_worth' and @id = 'ffInput_include_net_worth']</value>
      <webElementGuid>a3ed4060-10b0-4bd3-99c8-8b80df087132</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
