<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_dailyweeklymonthlyquarterlyevery hal_79c7c6</name>
   <tag></tag>
   <elementGuidId>22c81ea5-1e77-41eb-a06e-0c93b4b8b946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_repeat_freq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_repeat_freq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>048e2be5-fd44-418f-82ec-a711f8b5ca86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6c19549a-e281-4b0b-b7f9-2ad6839742ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeat_freq</value>
      <webElementGuid>d34df9f8-61f4-46d4-93be-a1f8e5c25df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_repeat_freq</value>
      <webElementGuid>7ba86b62-ee8e-4878-bfbb-ffbe0d61e04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>abc0a4a0-28b7-4fd3-b428-a8b316042091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3a92fb08-5ae8-42ee-a643-ba360327130f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dailyweeklymonthlyquarterlyevery half-yearyearly</value>
      <webElementGuid>216c4b55-a116-4b73-9291-048217e6a9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_repeat_freq&quot;)</value>
      <webElementGuid>c75f8e86-e0c2-4b97-b86e-95a10c023312</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_repeat_freq']</value>
      <webElementGuid>b94fe7ff-74ba-47e3-82b5-3a9fc8e36398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repeat_freq_holder']/div/select</value>
      <webElementGuid>0248f9ba-d7c6-4fb8-bb3b-90b4332e330b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repeats'])[1]/following::select[1]</value>
      <webElementGuid>02202f69-5888-426b-93ff-17a5da1d2bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/following::select[1]</value>
      <webElementGuid>1c7de97d-8999-4dd6-af27-d1267ebce99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip'])[1]/preceding::select[1]</value>
      <webElementGuid>3749143c-dcf8-498a-97e2-fff4db8349fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optional fields'])[1]/preceding::select[1]</value>
      <webElementGuid>518c29f4-c99a-4943-ae5f-ef193da4c2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>2f27d19f-021d-4cd3-a63f-701bf4eff8be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'repeat_freq' and @id = 'ffInput_repeat_freq' and (text() = 'dailyweeklymonthlyquarterlyevery half-yearyearly' or . = 'dailyweeklymonthlyquarterlyevery half-yearyearly')]</value>
      <webElementGuid>94b72005-4091-4939-8dae-b80348de0fc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
