<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Demo</name>
   <tag></tag>
   <elementGuidId>c2c155c6-b08c-4507-8467-874565cc9616</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.me-lg-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarResponsive']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43b34636-bb77-4774-99d2-0b131905a8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link me-lg-3</value>
      <webElementGuid>2cc56263-676c-49b3-8806-c3c8b8c1d90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.firefly-iii.org/</value>
      <webElementGuid>5b986bc0-9263-42bb-a365-a2f7175e61a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo</value>
      <webElementGuid>0a33f9dd-6fdc-4b26-a456-3687f3e375e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarResponsive&quot;)/ul[@class=&quot;navbar-nav ms-auto me-4 my-3 my-lg-0&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link me-lg-3&quot;]</value>
      <webElementGuid>c3c73d31-8115-4d9d-88d3-8f422a534635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarResponsive']/ul/li/a</value>
      <webElementGuid>31fe696a-a009-49ce-b2f2-e1324038580c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Demo')]</value>
      <webElementGuid>b569fe77-1b62-46f4-b489-03308e8b3da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::a[1]</value>
      <webElementGuid>4a58f2f9-0d9c-4df0-8509-2a27b654edd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firefly III'])[1]/following::a[1]</value>
      <webElementGuid>3407838d-4b95-448f-8ec3-f451d807dfa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentation'])[1]/preceding::a[1]</value>
      <webElementGuid>f828a949-0a3d-451d-9372-c5494cfaa6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::a[2]</value>
      <webElementGuid>c8138700-b0e7-45e8-850d-0eacc835fe32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo']/parent::*</value>
      <webElementGuid>29f740eb-8c25-483c-b9e9-cb957e651967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.firefly-iii.org/')]</value>
      <webElementGuid>dbfa86dc-2351-4794-a62c-309dd5371697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>8eff60d6-712e-4f83-9bed-6b1cc97b1ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.firefly-iii.org/' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>ebfe90c4-eed4-4851-9fa2-ecdac10f2734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
