<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maximum amount_amount_max</name>
   <tag></tag>
   <elementGuidId>57f0d0f3-ac86-4037-ba69-2137197b19b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_amount_max</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_amount_max']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ee456cc-ed32-4766-a834-4bc29c6ad299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>98a5685d-0006-4ad7-af16-5f6adbd380dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>92b300df-3538-4c95-83b1-115d20be743d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amount_max</value>
      <webElementGuid>b9cd9d58-f8da-4ba3-9bc6-3a294aac999d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_amount_max</value>
      <webElementGuid>7b56bf4a-a95d-4036-a25a-a588f3b78e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>b13aeaf3-73aa-4dbc-9609-b7ae60ab04f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ee61f2d3-a92f-45c1-919b-623812ac4396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6529b1f6-0a90-400c-81dd-c3d05a9e2f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_amount_max&quot;)</value>
      <webElementGuid>8879a27d-c298-44a6-8eed-71fb4b9d650e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_amount_max']</value>
      <webElementGuid>68c6ae08-fc89-4c3d-9155-5634dd76160a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amount_max_holder']/div/input</value>
      <webElementGuid>c797e37c-4fd9-4ea4-a0c6-c75c8765c75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>72078671-f3de-490a-a047-cae0138b5721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'amount_max' and @id = 'ffInput_amount_max']</value>
      <webElementGuid>5c47484f-1adf-4386-a42c-4b7c99ed464a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
