<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Create new bill</name>
   <tag></tag>
   <elementGuidId>3b52befc-69b5-4c30-b63f-80c528a1e3a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//small[@id='subTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>b3454ec3-5067-4022-8790-a4448ad33504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subTitle</value>
      <webElementGuid>5a9a5e9e-b4b9-4b21-967d-ad4f085ed33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Create new bill
</value>
      <webElementGuid>ff257df2-2205-4e99-9c76-feec82a42ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subTitle&quot;)</value>
      <webElementGuid>69aad83d-253f-4a48-a010-fd0986d59825</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//small[@id='subTitle']</value>
      <webElementGuid>aa5cb4e2-1ce3-4449-9588-b278ab648b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section/h1/small</value>
      <webElementGuid>4d583866-5900-43e7-8f61-bedc8bdfcaf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::small[1]</value>
      <webElementGuid>24ddeb0e-0f3f-466e-bc4c-7395681d8387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::small[1]</value>
      <webElementGuid>ac028be0-5449-49ad-859a-159aca0821c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bills'])[2]/preceding::small[1]</value>
      <webElementGuid>49002e0e-df82-47f5-a4e9-aa25308ffffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create new bill']/parent::*</value>
      <webElementGuid>269508a6-bb57-4916-a66b-4522b015b4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//small</value>
      <webElementGuid>e8af7952-09f1-495b-ab92-ae7df36ddefe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[@id = 'subTitle' and (text() = '
Create new bill
' or . = '
Create new bill
')]</value>
      <webElementGuid>1da2004b-57ed-4893-94ce-acd763b83162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
