<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Attachments_attachments</name>
   <tag></tag>
   <elementGuidId>c88fe471-c999-4163-b33b-30d334cd2ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_attachments</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_attachments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>989c5c82-1ae8-449e-9925-7d032ce2bcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>486d1425-d61c-43d2-a58b-8b51d5f95144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>a1b925a7-0b05-4f43-aa80-e568e8d972be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attachments[]</value>
      <webElementGuid>0c63a24d-f4cf-4d35-864d-bf638f7d90cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_attachments</value>
      <webElementGuid>1d3bed02-a405-4c45-97c1-ff6af184a425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>2b88968d-8a19-4d81-a387-d9d8d72bcea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_attachments&quot;)</value>
      <webElementGuid>6e258e3b-7971-461a-bac8-7753a2aed9ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_attachments']</value>
      <webElementGuid>257e759b-ac6c-4eb8-82d6-68ee7d3a81dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attachments[]_holder']/div/input</value>
      <webElementGuid>54580f59-b9d6-4396-981b-ef0abe82aff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>30e3c16d-b069-49a6-9b0d-668f1dba0c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'attachments[]' and @id = 'ffInput_attachments']</value>
      <webElementGuid>a3b72431-0cfc-492e-99b7-e812608e6fcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
