<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Include in net worth_include_net_worth</name>
   <tag></tag>
   <elementGuidId>18e6764c-cf54-41f1-86c9-efd2246c6fa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_include_net_worth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_include_net_worth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ceed6e2-fccc-410f-adcd-910b3fc2d562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>71e4f47b-aa36-4158-8669-faf346d5c916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>include_net_worth</value>
      <webElementGuid>d1f9f56e-548e-42e7-ba26-3974bcd99063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_include_net_worth</value>
      <webElementGuid>fa4739d3-0892-407f-bc0b-53236691716f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5d1e7114-3961-4eb0-8692-238548f11e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_include_net_worth&quot;)</value>
      <webElementGuid>f7a9e5f6-5c2f-4ecd-bf3b-c573afd82dd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_include_net_worth']</value>
      <webElementGuid>0850d868-d5ec-426e-813a-fd0cbdfcedb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='include_net_worth_holder']/div/div/label/input</value>
      <webElementGuid>73319291-ffde-4011-b0f0-abc93db028ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>1417de7c-644a-45cc-bfe7-f3eb5803d2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'include_net_worth' and @id = 'ffInput_include_net_worth']</value>
      <webElementGuid>4dc758e2-3454-46ef-b51c-41a23d2be162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
