<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>center_nginx1.18.0 (Ubuntu)</name>
   <tag></tag>
   <elementGuidId>302ddc81-c5ae-4a6f-ae80-29e20af2117b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>center:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//center[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>36043862-aace-4c0c-a20b-380a06c18749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nginx/1.18.0 (Ubuntu)</value>
      <webElementGuid>efe7abd0-d0a5-44ae-8b3c-9355f3f46214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[2]</value>
      <webElementGuid>9beea553-cb76-4350-ad28-3adb88bce079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center[2]</value>
      <webElementGuid>a1dde1b2-3b92-44a8-b06c-4b58087d80bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//center[(text() = 'nginx/1.18.0 (Ubuntu)' or . = 'nginx/1.18.0 (Ubuntu)')]</value>
      <webElementGuid>50365de9-ea29-43e4-bfeb-e7f37d740763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
