<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_413 Request Entity Too Large</name>
   <tag></tag>
   <elementGuidId>fc5f090b-0bd1-4482-b1e5-b076d3fbc419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>116d0cf3-e9ba-4f4c-8b97-5d3a607ebade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>413 Request Entity Too Large</value>
      <webElementGuid>04881886-b064-43ed-adae-8110ff4ac997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/h1[1]</value>
      <webElementGuid>3b08663b-a61c-4e9a-97ab-cad3ec7d4381</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>506146fc-2917-4642-8e39-3034b6ff19ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '413 Request Entity Too Large' or . = '413 Request Entity Too Large')]</value>
      <webElementGuid>ec2499cf-3d7a-4cb8-806d-cf0cbf5d8c19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
