<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Attachments_attachments</name>
   <tag></tag>
   <elementGuidId>6d88d20b-cbeb-4d2b-bf5a-dfdf2686bbf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_attachments</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_attachments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>467745e9-d305-435b-a293-efe0eccc265c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4221ad1d-3138-4862-9770-6e9d6d85f973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>e4feca23-1e6f-415d-9ead-3496768969a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attachments[]</value>
      <webElementGuid>325e5925-e90d-46d9-b957-1d918f266d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_attachments</value>
      <webElementGuid>bfa488ec-45ff-43c7-9819-7962cc103de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>cc19b590-873f-4a9d-a81f-a541b9b0f0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_attachments&quot;)</value>
      <webElementGuid>11152432-50a8-4b49-b62e-b4c728134522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_attachments']</value>
      <webElementGuid>689eb93a-bca6-4124-a774-a4c1f515b0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attachments[]_holder']/div/input</value>
      <webElementGuid>e1756e12-5231-4dd4-83a9-91a54bc8f54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[4]/div/input</value>
      <webElementGuid>2e3161bc-ae43-4397-b434-a4177aa5cbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'attachments[]' and @id = 'ffInput_attachments']</value>
      <webElementGuid>29981109-5ec8-4510-b0b3-b055aaaf727d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
