<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_After storing, return here new budget</name>
   <tag></tag>
   <elementGuidId>dc406caa-aeea-46fb-8c84-c86c2e04344b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#budget_return_to_form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='budget_return_to_form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dfbb72b-952f-4f2f-b132-37d423a81362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>717c9396-87fb-47ee-a088-a97fa7934837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create_another</value>
      <webElementGuid>309016a0-aae6-4826-a027-178fa06807bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>budget_return_to_form</value>
      <webElementGuid>80722bf0-8feb-4037-a049-8e870db0a733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>69ddd207-b4e5-4ad2-b669-3020b4603aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;budget_return_to_form&quot;)</value>
      <webElementGuid>00e090ff-af2a-4ce0-a096-91a6f931e7e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='budget_return_to_form']</value>
      <webElementGuid>1f88df9f-5561-4714-ab0f-0488135d840a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='store']/div[2]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>41642d0c-7f63-43d8-9b3d-810e20fc1a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>87f8485d-0129-45a9-8117-39cff7e0aa73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'create_another' and @id = 'budget_return_to_form']</value>
      <webElementGuid>0a53d0f0-428b-4cac-a0e1-2bdb01137638</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
