<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Demo</name>
   <tag></tag>
   <elementGuidId>59c5e975-8923-4e06-89b3-f34fbcf5de32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.me-lg-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarResponsive']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7fd779e-a16a-4847-a521-afa17c995988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link me-lg-3</value>
      <webElementGuid>02df92c1-1ee7-40d7-a689-b1e03ed420a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.firefly-iii.org/</value>
      <webElementGuid>2d32885a-80b8-45fc-a52d-f9b3448cf3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo</value>
      <webElementGuid>5b159a0f-6d11-48f6-9dfd-b9557aaf52a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarResponsive&quot;)/ul[@class=&quot;navbar-nav ms-auto me-4 my-3 my-lg-0&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link me-lg-3&quot;]</value>
      <webElementGuid>79d99078-551f-4d1d-8975-0e02eab6b874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarResponsive']/ul/li/a</value>
      <webElementGuid>2be27b63-fd2a-479a-b208-07892c1a0c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Demo')]</value>
      <webElementGuid>63f635db-c7dd-4e69-b500-9640d0bef7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::a[1]</value>
      <webElementGuid>ed16bfb4-cd2d-4b15-b5e9-c062e6505d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firefly III'])[1]/following::a[1]</value>
      <webElementGuid>56755849-850c-4771-853c-6c078ce39b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentation'])[1]/preceding::a[1]</value>
      <webElementGuid>45360eba-e01f-434e-8205-643b793edf52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::a[2]</value>
      <webElementGuid>ad861f7d-3680-4e5d-a94d-7b17fadd7d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo']/parent::*</value>
      <webElementGuid>0b7a4ce5-5a8b-4d8e-b420-e2eeeda408b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.firefly-iii.org/')]</value>
      <webElementGuid>5be92dfb-808f-4e9a-92e4-957b0713ff04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>c58eebdd-e83f-4ca2-9e75-2f8199261fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.firefly-iii.org/' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>62ea7968-7030-47f6-b1be-0adbeedec7cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
