<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GUI_Create_New_Bill</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>73ff9043-b8e7-4540-a43a-8efd9442f865</testSuiteGuid>
   <testCaseLink>
      <guid>4d6301ef-5c8a-4b9b-8c4b-1e39c8e226e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0922c21e-cbc3-4b5c-969e-cc2af6c836c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>828e0421-2e34-4cd9-bd44-cd1a8e72e930</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57a856d4-49d7-4015-9055-8f52bfb589e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc1ed78f-eac7-48c7-8d40-e27e416505c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68d2ee41-8573-40a7-991d-41c51b4b504b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d7ac2e4-d9ac-40fe-8b68-85df39b5b534</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d4fcc98d-ec3b-41cb-a527-056a2b7f5254</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd473c4a-6834-4395-9cfa-c3a06f17adaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>812537a1-7797-4638-a840-81a368677d09</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>effbd0cc-22ee-4d1e-a867-5fb7e437e054</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dcbf0b9-7faa-4b82-ab6b-aa75736c9148</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>942e1384-8836-4dcc-8042-3f8f2a4ff32a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22c96bb1-007a-4c20-9967-732679ec91cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0115e0ce-35db-42d7-94b4-bf205d3f1171</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e753de9-c079-450d-af84-9b45147dcf57</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ac0426f-6cf7-42d6-8f2b-e379e7cc3a74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>206a7247-a44f-4349-af44-26e6978439ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7b64a8e-39d1-4d91-9156-4c2507b11461</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e78e020b-c587-4f01-beec-2422a14aeb03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e99fd4c5-bf9e-4e26-900f-bda95ff54bcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>468def90-85f3-49a0-8cd8-9e110b7869c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d3cabc2-3ad3-4099-94f0-6dac0471d063</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f90cf36-c4af-45fa-918a-340b085b25cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b195d5d3-51aa-4b45-a9a4-92b66c0a44e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5b5f8dd-9b0d-4435-8553-089177aaa1b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3efe57fa-504e-4148-b286-0f96883345d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34e996e2-0468-40dc-a594-3a5ee7feaa15</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57f94f2a-2498-449d-af06-67209adf6b08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96a141c5-58d7-4e8b-92de-b2095b91284f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cafd29a7-252c-4a44-ba5e-272351843848</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f1c0ee7-84a3-4e0b-8d06-727b461f1c5b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88b25bf2-cc67-49c4-a0ef-1a7ce21de57c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c1e806a-eba8-4dff-a0f3-f9dfe016165d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4da9221-853f-497f-b651-62294e742172</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d29f825-c50b-4f52-b10a-5461220fe06f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d5b58d5-32f1-4dcf-852f-316878c61eec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66504b0c-e097-4f30-98cb-746cf624c125</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63351734-046b-45c8-9c42-3072c3924c63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b7c8722-8e7f-4636-85e4-165cd529789e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>000c958b-c108-4c9b-9640-56e0601433c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Bill/TC_9.15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
