<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GUI_Create_New_Liability</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e4f96773-7e32-45a1-8fa6-82c2e51e6429</testSuiteGuid>
   <testCaseLink>
      <guid>6367625f-d721-4fe0-a24a-0c417477f48c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>537a72e5-feda-42ec-9f04-33879213296a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34d15db4-3d96-4881-9f50-1ff79e84beac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95ad5f1b-7284-419d-943c-0c2cda7e5cd3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98b0429a-2c39-4fae-8185-27f4e6ae3d2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af93ae93-c3d7-42ac-ad99-82044f425bb7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58dd974b-56e2-4618-a691-e04375be9577</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df21b8be-ceb1-4ca0-ad83-e399c8e67857</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd70f320-db97-49c7-b07f-15df3fb3b903</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>849e19c0-08d0-4eb2-9c7e-da037a30fe08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9596bc91-a05d-43f9-892b-baf305eed4a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e86405e-48ef-486c-8cbc-8d45ec2837fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1b2963b-0a9b-4665-9818-3bfdfc897556</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55764589-7eda-495f-9f5c-372247aea49f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f4bb175-dc8d-4afc-9325-92b1ad61f0c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8894c40b-d5e7-4edc-af3c-649ce99973b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86bb9906-f97c-4e17-9ac0-6ab76d822afd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65b7760f-fe25-4d88-975b-c4817402b150</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f783129f-281e-4030-8fbf-3391c4856333</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8caa603d-e421-4914-ac17-3aef39559561</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>560b697c-c5be-4adb-9c1e-49951d4d25df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2db137f9-b508-4674-9c34-8ab57493f173</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82860408-9a2b-4595-93bf-ef30b91565d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56ca559b-47a7-4a77-8602-2d594991f674</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87c5ef4a-5a50-4a27-b0b9-76654dbc8e37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92d22f4f-a864-4da4-8814-b8e4f359179f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4c51dfd-8d85-4695-a3c2-1fc0ab8077bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38dcffd3-2bb1-4c33-a808-fa22b1d3efe1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>061c2106-24ae-4fbc-9dd9-f65699b04745</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48a83d48-df5b-4c9d-83a6-1b80877756ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ef63971-7faf-4114-b457-4ed277efa811</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36de85d7-8d2d-4479-8bee-2875fa8c2e76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2bd919a1-4869-4692-9546-54eb5811fbb6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8edfe0c9-e175-4946-b301-824f3ed3b996</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>917c527a-c215-40b2-86c1-2ccc0155a7da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c94218a-d766-4ac2-9708-1790608fca0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebcb457f-e0a8-4557-bb12-815fc92163bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc803c40-2a36-4270-9454-95cd66d1db3b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c5fb4df-3f83-4977-b2a8-e975e23e0445</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>175c8403-7492-4559-a448-be99a5a3d334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84e60649-77d6-4091-8a79-9c31264b34ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44d8d689-abc1-46ba-a573-14bf61ba4e4d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>741ba6d4-ad04-45b0-a752-c96f2bad3306</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73a88a26-b9f4-4a18-a41f-28a0692c46fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d64b89f-3182-4ce4-9215-093623ccc41e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.16</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a64cbab-4b78-4c63-ba4d-0539ab91c4ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>092bfce6-2f31-4457-a347-7a43bc3cb4f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5f622e6-39a1-4d8a-ba60-4298a84b962f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI_Create_New_Liability/TC_10.17</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
