<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date_date</name>
   <tag></tag>
   <elementGuidId>705046b5-abb3-4478-8d9a-6e75cddea11f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ce9446d-81a0-4415-be20-3384a94461cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7697efa4-6331-46f8-93e9-af8237f35e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>65537a37-de12-4fb3-b3ab-505483748f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>41832467-9e11-473e-b4d5-f42b7cfe2240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_date</value>
      <webElementGuid>6d320a5e-9a63-4461-b87a-ee00cc89c41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2024-01-06</value>
      <webElementGuid>93b0940d-f2fd-4069-8c78-ffcc6cefe7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8ebc41ff-e0f4-4da4-b2e9-0070913bc80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce930923-61ce-4bb5-a4a0-541886e75aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_date&quot;)</value>
      <webElementGuid>ec9b1a14-4b5e-46ee-8909-4245c1bc7551</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_date']</value>
      <webElementGuid>6786b2d6-5ba4-4f4f-a84c-dba87d45686b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='date_holder']/div/div/input</value>
      <webElementGuid>b748d723-c84b-4016-8fd5-ea8252473b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>ef89f893-49ec-412b-afba-99db633cf741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'date' and @id = 'ffInput_date']</value>
      <webElementGuid>d7cd25f6-206c-42ac-b5db-1c9e5ec341e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
