<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Attachments_attachments</name>
   <tag></tag>
   <elementGuidId>608e53af-b79c-48a7-8a0d-043e8f96442c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_attachments</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_attachments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74e292a9-8fbd-4f3e-86bf-785941138235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6ec716ce-c2b6-4075-b87e-c5ed5e23a331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>acc6a539-2ed2-47ad-af3f-e8b14ec61f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attachments[]</value>
      <webElementGuid>92d4956d-2aa4-4ecc-8e36-7ae9e92e5e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_attachments</value>
      <webElementGuid>47e7a6db-b98a-4fa7-bd7a-c2b13d310338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>a95aae9e-cdab-4659-8944-fd5e1183fdf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_attachments&quot;)</value>
      <webElementGuid>8e1c3c5a-678d-4eb0-92ab-0ec01fa67bdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_attachments']</value>
      <webElementGuid>0eca5138-bb84-4e67-8d5f-ea6b4016a74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attachments[]_holder']/div/input</value>
      <webElementGuid>de670a6e-f68a-4d22-902f-a9fc415ea252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[4]/div/input</value>
      <webElementGuid>57427ca7-f389-46d7-921f-ce00010ca6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'attachments[]' and @id = 'ffInput_attachments']</value>
      <webElementGuid>ddc3bff3-aa7f-4c6c-ae96-ce9e6068e75f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
