<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_dailyweeklymonthlyquarterlyevery hal_79c7c6</name>
   <tag></tag>
   <elementGuidId>0f2cd22d-625e-479e-94a5-e07cfb015c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_repeat_freq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_repeat_freq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>11f0cbd1-4251-4525-849d-4f6079f841ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ad6730d0-0216-46a4-93a2-7d9a2e23a404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeat_freq</value>
      <webElementGuid>b4f16c06-4045-41d3-982a-9ee05eedb2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_repeat_freq</value>
      <webElementGuid>1a6a51ff-76fe-4bf4-bcd5-eecc50683918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d7d65c8c-9d5f-4969-be52-7f44acd3685f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>50a49763-e8c3-41c6-8593-2541f05c8d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dailyweeklymonthlyquarterlyevery half-yearyearly</value>
      <webElementGuid>09f9b2b6-b248-4050-8fee-387ff0dd02b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_repeat_freq&quot;)</value>
      <webElementGuid>bde1ab01-2af9-4bfc-84e7-a9eabf4d6bc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_repeat_freq']</value>
      <webElementGuid>095065d8-ecc8-4a19-92d5-994fb928d22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repeat_freq_holder']/div/select</value>
      <webElementGuid>e881dbde-173b-4f95-b218-7c480bf123a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repeats'])[1]/following::select[1]</value>
      <webElementGuid>e3479506-4111-4f19-8bf6-5c26731a5990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/following::select[1]</value>
      <webElementGuid>43c00ad3-d642-4c30-ba8e-6379ded8cd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip'])[1]/preceding::select[1]</value>
      <webElementGuid>927a5026-90b2-4eca-af78-14bec4c9b109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optional fields'])[1]/preceding::select[1]</value>
      <webElementGuid>dd49dbac-4ed1-4729-a774-efed78b4ee7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>4b784736-ba08-4843-bc22-659bcd320b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'repeat_freq' and @id = 'ffInput_repeat_freq' and (text() = 'dailyweeklymonthlyquarterlyevery half-yearyearly' or . = 'dailyweeklymonthlyquarterlyevery half-yearyearly')]</value>
      <webElementGuid>8dcfc870-4a63-43dd-872e-9075927d9e3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
