<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_demofirefly_fa fa-plus-circle</name>
   <tag></tag>
   <elementGuidId>a16d8913-1690-43dd-aca4-4e81b903388e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-plus-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sidebar-toggle']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0490330d-6b01-4b51-a815-4eab8ba74652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus-circle</value>
      <webElementGuid>c82e8951-3c46-4f22-b584-3069446d14fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-toggle&quot;)/a[1]/span[@class=&quot;fa fa-plus-circle&quot;]</value>
      <webElementGuid>a14fb917-246d-46cc-8188-e06935f3ab24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sidebar-toggle']/a/span</value>
      <webElementGuid>2c6e5dd3-6aaa-432c-aad4-f099b0e8b3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>4734176b-0208-42ad-95ee-1ec70150590e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
