<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_The minimum amount field is required</name>
   <tag></tag>
   <elementGuidId>1f654867-bc7f-4c8a-a4c6-ae49fd1e4de7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amount_min_holder > div.col-sm-8 > p.text-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='amount_min_holder']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7f48e748-b71e-4456-9068-c35719705ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>a3836960-eb3e-4fa3-b3e1-55263d85169f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The minimum amount field is required.</value>
      <webElementGuid>841849bb-fb2c-447d-8cee-191daf0fbd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount_min_holder&quot;)/div[@class=&quot;col-sm-8&quot;]/p[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>05ec9411-53ff-4984-8781-dd572d2613c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amount_min_holder']/div/p</value>
      <webElementGuid>b0d7b5a8-7d0d-49fb-a51e-3ce97927114d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum amount'])[1]/following::p[1]</value>
      <webElementGuid>38dfa5ab-3e10-491d-b6f6-e08e22b3faf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::p[1]</value>
      <webElementGuid>7bf8830e-c851-4e0c-80d0-d4d23bb78e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum amount'])[1]/preceding::p[1]</value>
      <webElementGuid>7464e96e-1c54-4325-9822-238740e42c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::p[2]</value>
      <webElementGuid>4c132862-061a-42f6-b48f-f05e4c4e5e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The minimum amount field is required.']/parent::*</value>
      <webElementGuid>36b57994-af0a-43f4-aeb0-6ee5933363e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p</value>
      <webElementGuid>db85fcab-f56b-447d-930c-b6adc1e034eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'The minimum amount field is required.' or . = 'The minimum amount field is required.')]</value>
      <webElementGuid>275057cd-eda1-4a4b-a82f-a9ffc99f4516</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
