<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_The maximum amount field is required</name>
   <tag></tag>
   <elementGuidId>ef62b4b8-1bbe-4f8e-a1c6-6e3190aab56d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amount_max_holder > div.col-sm-8 > p.text-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='amount_max_holder']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ca6513a0-a3bb-4de9-95d0-1e0e890c720a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>e739b61c-d572-4600-8287-cffa654595da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The maximum amount field is required.</value>
      <webElementGuid>9ffd8b1f-47e4-43da-98f6-de8ab6022b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount_max_holder&quot;)/div[@class=&quot;col-sm-8&quot;]/p[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>5645c85e-d103-4c6d-b069-17c489733601</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amount_max_holder']/div/p</value>
      <webElementGuid>89b489bf-2114-4260-aee2-6de927641d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum amount'])[1]/following::p[1]</value>
      <webElementGuid>058f36d5-62bb-4bd2-9212-5d40138e1c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum amount'])[1]/following::p[2]</value>
      <webElementGuid>4098e93f-43c6-4558-a446-4c0243319ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::p[1]</value>
      <webElementGuid>c91da3c6-c001-4601-8d70-2fdabb295c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repeats'])[1]/preceding::p[1]</value>
      <webElementGuid>b9dfe124-9596-4eac-84f9-58fe5031f405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The maximum amount field is required.']/parent::*</value>
      <webElementGuid>10f41855-70b1-4321-811c-a8159a81eabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/p</value>
      <webElementGuid>6310ff3b-fa9c-4787-a204-c2f0ba31db71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'The maximum amount field is required.' or . = 'The maximum amount field is required.')]</value>
      <webElementGuid>ad59f6ed-89ab-4a72-9d68-f5f3f572015c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
