<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_After storing, return here to create _4fc2e2</name>
   <tag></tag>
   <elementGuidId>a61ab461-ce4e-46a9-ac41-5eabf8e5abef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bill_return_to_form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bill_return_to_form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>894a6281-5111-44be-a190-8cebfae25537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3f463063-92cb-475e-8c49-aa3b7f5afa7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create_another</value>
      <webElementGuid>b099e88e-6105-4502-9763-d2d4db070314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bill_return_to_form</value>
      <webElementGuid>808c4015-4ab0-45a9-87a4-647096dd92c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6a308bcb-74ed-4c90-958f-9087f4355111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bill_return_to_form&quot;)</value>
      <webElementGuid>ccd96449-886a-4456-84f2-5fb8d39c9bf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bill_return_to_form']</value>
      <webElementGuid>2875bb3a-64d3-4081-9a72-680c522d4f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='store']/div[2]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>e5f71c73-eb3b-44cc-a5cc-86e69f9d9c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>c2c75d89-4d17-4b1e-aa87-609501902ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'create_another' and @id = 'bill_return_to_form']</value>
      <webElementGuid>2cfb1157-6ca8-4a6e-af53-21dad5c4fedb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
