<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Date_fa fa-calendar</name>
   <tag></tag>
   <elementGuidId>626c08a1-663c-4b69-8ac7-7d47ab1b9da8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='date_holder']/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ca991d07-1229-4f2e-b566-42a6ac9e59c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-calendar</value>
      <webElementGuid>2fc3a44a-d471-40ce-a632-f6431bc7b970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date_holder&quot;)/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;input-group-addon&quot;]/span[@class=&quot;fa fa-calendar&quot;]</value>
      <webElementGuid>6e465cf7-7335-4236-92f4-672fbb952902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='date_holder']/div/div/div/span</value>
      <webElementGuid>bf1e98f5-b1fb-40f0-a780-09569808be51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/span</value>
      <webElementGuid>b7eb22fb-3249-4767-8b6d-282f73cb9f96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
