<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_demofirefly_fa fa-plus-circle</name>
   <tag></tag>
   <elementGuidId>962fc6fe-de70-4944-bd49-7ec20bf40468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-plus-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sidebar-toggle']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3d41a28c-e7cf-41f5-a23c-a3b07a89eb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus-circle</value>
      <webElementGuid>c84e0ac4-551f-491c-bf11-6b25fa7b8abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-toggle&quot;)/a[1]/span[@class=&quot;fa fa-plus-circle&quot;]</value>
      <webElementGuid>ae4ead2c-6dd7-4200-ad6b-2f8bd5db97b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sidebar-toggle']/a/span</value>
      <webElementGuid>72af7b9c-47a6-48e1-a930-169669b64079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>d6d679f2-adca-43f9-a426-454c8e7abe60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
