<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Per dayPer monthPer year</name>
   <tag></tag>
   <elementGuidId>fe80671a-26ed-4cd4-b420-ad26eb4d2f19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_interest_period</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_interest_period']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5e0eecd2-fedd-4bc4-95fe-8c1dbfcc7fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>edd88cc7-81fb-4695-aea9-4f25a582d4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>interest_period</value>
      <webElementGuid>ed581b78-1185-42a4-a535-b502d574ee69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_interest_period</value>
      <webElementGuid>204048d4-0246-4063-ae5e-e230fb5d5c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c946f2dd-842a-40fc-96ad-8624cba03e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>937e0880-996e-4701-9f7d-c9458f2a1940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Per dayPer monthPer year</value>
      <webElementGuid>fd8cc89c-0893-488e-a8d6-1703d7521749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_interest_period&quot;)</value>
      <webElementGuid>cfecfaf7-69d0-4e34-b1b4-8b378dce68f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_interest_period']</value>
      <webElementGuid>202748c8-2948-4958-a680-aab9e682fa8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='interest_period_holder']/div/select</value>
      <webElementGuid>98c3ccd8-7986-4dcd-9100-a6a403279709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest period'])[1]/following::select[1]</value>
      <webElementGuid>2e9394e1-3b18-47f8-9784-caf40abbb79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/following::select[1]</value>
      <webElementGuid>a02440e7-700d-4a04-92c8-7b5eec43e3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optional fields'])[1]/preceding::select[1]</value>
      <webElementGuid>d2585fd3-059d-4e2b-aac0-3ff8226152b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IBAN'])[1]/preceding::select[1]</value>
      <webElementGuid>93590b3a-50a0-463a-bb9a-e7661e85198f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>ad9b3ad6-8d96-4597-9141-db65e030c658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'interest_period' and @id = 'ffInput_interest_period' and (text() = 'Per dayPer monthPer year' or . = 'Per dayPer monthPer year')]</value>
      <webElementGuid>0fbdfcdd-c87c-44db-8c07-554c9944ed71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
